### PR TITLE
Modal visibility when screen is between 640px to 1027px

### PR DESCRIPTION
**Pull request by Ujairul-CX-git**
Please find the image below:
Modal is not showing in a certain range of screen sizes.
modal_visibilty_issue

Changes made:
modal_1

Output:
mdoal_2

### CODE REVIEW

**Comment by acidjazz** [comment]
@Ujairul-CX-git I would look at modifying the actual source files instead of the generated `dist/` like [here](https://github.com/acidjazz/tv-modal/blob/master/src/ModalBase.vue#L24)


I would also in the future keep an eye on https://github.com/fumeapp/tailvue since most of our progress is now moving to this package

**Comment by Ujairul-CX-git** [comment]
> @Ujairul-CX-git I would look at modifying the actual source files instead of the generated `dist/` like [here](https://github.com/acidjazz/tv-modal/blob/master/src/ModalBase.vue#L24)
> 
> I would also in the future keep an eye on https://github.com/fumeapp/tailvue since most of our progress is now moving to this package

Sure will do that! Thanks for pointing it out @acidjazz!

**Comment by nilanjan-codelogicx** [comment]
> > @Ujairul-CX-git I would look at modifying the actual source files instead of the generated `dist/` like [here](https://github.com/acidjazz/tv-modal/blob/master/src/ModalBase.vue#L24)
> > I would also in the future keep an eye on https://github.com/fumeapp/tailvue since most of our progress is now moving to this package
> 
> Sure will do that! Thanks for pointing it out @acidjazz!

@acidjazz Can you please review this fix please? Thanks in advance!

**Comment by acidjazz** [comment]
@nilanjan-codelogicx sure! do me a favor and remove the compiled file changes in dist/ and then i'll have those generated when i issue a release

**Comment by Ujairul-CX-git** [comment]
> @nilanjan-codelogicx sure! do me a favor and remove the compiled file changes in dist/ and then i'll have those generated when i issue a release

@acidjazz I have made the changes you requested. Please let me know if any other changes you want here.

**Comment by acidjazz** [comment]
@Ujairul-CX-git https://github.com/acidjazz/tv-modal/releases/tag/v1.0.25 👏

**Pull request merged**
